from env import *

SENTIMENTAL_NEWSLETTER_LOG_PATH = 'gpt_sentimental_newsletter_logs/'

REDDIT_CLIENT_ID = REDDIT_CLIENT_IDenv
REDDIT_CLIENT_SECRET = REDDIT_CLIENT_SECRETenv
REDDIT_USERNAME = REDDIT_USERNAMEenv
REDDIT_PASSWORD = REDDIT_PASSWORDenv
REDDIT_USER_AGENT = REDDIT_USER_AGENTenv
REDDIT_COUNT = 1
STOCK_COMMENT_MIN_COUNT = 3

SUBREDDITS_TO_QUERY = ['stocks', 'wallstreetbets']
KNOWN_NOT_STOCKS = ['UPVOTE', 'SUPPORT', 'YOLO', 'CLASS', 'ACTION', 'LAWSUIT', 'AGAINST', 'VALHALLA', 'MOON', 'PE', 'COVID', 'IMO', 'IPO', 'BTC', 'PUT', 'CALL','ROBINHOOD', 'GAIN', 'LOSS', 'PORN', 'WSB', 'I', 'STILL', "DIDN'T", 'HEAR', 'EBITDA', 'SQUEEZE', 'BS', 'VIX', 'FUD', 'HUT', 'ITM', 'OTM', 'NO', 'BELL', 'CEO', 'CFO', 'DD', 'MOASS', 'STONK', 'MEME', 'DICK', 'FOMO', 'EV', 'PIPE', 'HOLD', 'OTC', 'NOKPF', 'TTM', 'SPY', 'EVER', 'TO', 'A', 'THE', 'FUCK', 'US', 'FUCKING', 'ARE', 'DD', 'US', 'TLDR', 'EDIT', 'IV', 'SP500', 'SEC', 'GLOBE', 'NEWSWIRE', 'PT', 'NYSE', 'SPAC', 'FDA', 'DNA', 'HODL', 'USDA', 'PTSD', 'ETF', 'LLC', 'CSE', 'USA', 'EPS', 'BUY', 'B', 'AM', 'PM', 'SI', 'SP', 'TBA', 'TBD', 'TA', 'AI', 'LINK','CLICK', 'IRA', 'LIVE', 'NEXT', 'FID', 'UK', 'IP', 'FOMC', 'HOUR', 'API', 'SIP', 'FREE', 'NASDAQ', 'VOTE', 'NSFW', 'PGA','LIV', 'LOL', 'WEED', 'OP', 'AH', 'PL', 'VR', 'AR', 'FB', 'YTD', 'WSJ', 'NOT', 'ATH', 'CPI', 'CNBC', 'NBC', 'ADD', 'SERIOUS', 'FYI', 'GPT', 'DCA', 'FOR', 'BTFD', 'RIF']

GPT_MIN_COMMENT_COUNT = 4
GPT_SECRET_KEY = GPT_SECRET_KEYenv
GPT_MODEL = 'gpt-3.5-turbo-16k-0613' #'gpt-3.5-turbo-16k', 'text-davinci-003'


MAIL_SMTP_SERVER = 'smtp.gmail.com'
MAIL_SMTP_PORT = 587
MAIL_SMTP_USERNAME = MAIL_SMTP_USERNAMEenv
MAIL_SMTP_PASSWORD = MAIL_SMTP_PASSWORDenv
MAIL_DISPLAY_NAME = 'SENTIMENTAL_Trading'

AWS_S3_BUCKET_NAME = AWS_S3_BUCKET_NAMEenv
AWS_REGION = AWS_REGIONenv
AWS_ACCESS_KEY = AWS_ACCESS_KEYenv
AWS_SECRET_KEY = AWS_SECRET_KEYenv